<i>Copyright (c) Recommenders contributors.</i>

<i>Licensed under the MIT License.</i>

# LightGCN - simplified GCN model for recommendation

This notebook serves as an introduction to LightGCN [1], which is an simple, linear and neat Graph Convolution Network (GCN) [3] model for recommendation.

In [1]:


# Install recommenders library. It should pick up the compatible numpy version.
# If recommenders was already installed, this will ensure dependencies are correct.
!pip install recommenders
# Uninstall numpy 2.0.x if already installed, and install a compatible version
!pip uninstall -y numpy
!pip install numpy==1.26.4

Requirement already satisfied: recommenders in /usr/local/lib/python3.12/dist-packages (1.2.1)
Requirement already satisfied: category-encoders<3,>=2.6.0 in /usr/local/lib/python3.12/dist-packages (from recommenders) (2.9.0)
Requirement already satisfied: cornac<3,>=1.15.2 in /usr/local/lib/python3.12/dist-packages (from recommenders) (2.3.5)
Requirement already satisfied: hyperopt<1,>=0.2.7 in /usr/local/lib/python3.12/dist-packages (from recommenders) (0.2.7)
Requirement already satisfied: lightgbm<5,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from recommenders) (4.6.0)
Requirement already satisfied: locust<3,>=2.12.2 in /usr/local/lib/python3.12/dist-packages (from recommenders) (2.43.3)
Requirement already satisfied: memory-profiler<1,>=0.61.0 in /usr/local/lib/python3.12/dist-packages (from recommenders) (0.61.0)
Requirement already satisfied: nltk<4,>=3.8.1 in /usr/local/lib/python3.12/dist-packages (from recommenders) (3.9.1)
Requirement already satisfied: notebook<8,>=6.5.5 in /usr/local/lib/python3.12/dist-packages (from recommenders) (6.5.7)
Requirement already satisfied: numba<1,>=0.57.0 in /usr/local/lib/python3.12/dist-packages (from recommenders) (0.60.0)
Requirement already satisfied: pandas<3.0.0,>2.0.0 in /usr/local/lib/python3.12/dist-packages (from recommenders) (2.2.2)
Requirement already satisfied: retrying<2,>=1.3.4 in /usr/local/lib/python3.12/dist-packages (from recommenders) (1.4.2)
Requirement already satisfied: scikit-learn<2,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from recommenders) (1.6.1)
Requirement already satisfied: scikit-surprise>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from recommenders) (1.1.4)
Requirement already satisfied: seaborn<1,>=0.13.0 in /usr/local/lib/python3.12/dist-packages (from recommenders) (0.13.2)
Requirement already satisfied: transformers<5,>=4.27.0 in /usr/local/lib/python3.12/dist-packages (from recommenders) (4.57.6)
Requirement already satisfied: pandera>=0.15.0 in /usr/local/lib/python3.12/dist-packages (from pandera[strategies]>=0.15.0; python_version >= "3.9"->recommenders) (0.29.0)
Requirement already satisfied: statsmodels>=0.14.4 in /usr/local/lib/python3.12/dist-packages (from recommenders) (0.14.6)
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from category-encoders<3,>=2.6.0->recommenders) (2.0.2)
Requirement already satisfied: patsy>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from category-encoders<3,>=2.6.0->recommenders) (1.0.2)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from category-encoders<3,>=2.6.0->recommenders) (1.16.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from cornac<3,>=1.15.2->recommenders) (4.67.3)
Requirement already satisfied: powerlaw in /usr/local/lib/python3.12/dist-packages (from cornac<3,>=1.15.2->recommenders) (2.0.0)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from hyperopt<1,>=0.2.7->recommenders) (1.17.0)
Requirement already satisfied: networkx>=2.2 in /usr/local/lib/python3.12/dist-packages (from hyperopt<1,>=0.2.7->recommenders) (3.6.1)
Requirement already satisfied: future in /usr/local/lib/python3.12/dist-packages (from hyperopt<1,>=0.2.7->recommenders) (1.0.0)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.12/dist-packages (from hyperopt<1,>=0.2.7->recommenders) (3.1.2)
Requirement already satisfied: py4j in /usr/local/lib/python3.12/dist-packages (from hyperopt<1,>=0.2.7->recommenders) (0.10.9.9)
Requirement already satisfied: configargparse>=1.7.1 in /usr/local/lib/python3.12/dist-packages (from locust<3,>=2.12.2->recommenders) (1.7.3)
Requirement already satisfied: flask-cors>=3.0.10 in /usr/local/lib/python3.12/dist-packages (from locust<3,>=2.12.2->recommenders) (6.0.2)
Requirement already satisfied: flask-login>=0.6.3 in /usr/local/lib/python3.12/dist-packages (from locust<3,>=2.12.2->recommenders) (0.6.3)
Requirement already satisfied: flask>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from locust<3,>=2.12.2->recommenders) (3.1.3)
Requirement already satisfied: gevent!=25.8.1,<26.0.0,>=24.10.1 in /usr/local/lib/python3.12/dist-packages (from locust<3,>=2.12.2->recommenders) (25.9.1)
Requirement already satisfied: geventhttpclient>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from locust<3,>=2.12.2->recommenders) (2.3.9)
Requirement already satisfied: msgpack>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from locust<3,>=2.12.2->recommenders) (1.1.2)
Requirement already satisfied: psutil>=5.9.1 in /usr/local/lib/python3.12/dist-packages (from locust<3,>=2.12.2->recommenders) (5.9.5)
Requirement already satisfied: pytest<10,>=8.3.3 in /usr/local/lib/python3.12/dist-packages (from locust<3,>=2.12.2->recommenders) (8.4.2)
Requirement already satisfied: python-engineio>=4.12.2 in /usr/local/lib/python3.12/dist-packages (from locust<3,>=2.12.2->recommenders) (4.13.1)
Requirement already satisfied: python-socketio>=5.13.0 in /usr/local/lib/python3.12/dist-packages (from python-socketio[client]>=5.13.0->locust<3,>=2.12.2->recommenders) (5.16.1)
Requirement already satisfied: pyzmq>=25.0.0 in /usr/local/lib/python3.12/dist-packages (from locust<3,>=2.12.2->recommenders) (26.2.1)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from locust<3,>=2.12.2->recommenders) (2.32.4)
Requirement already satisfied: werkzeug>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from locust<3,>=2.12.2->recommenders) (3.1.6)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk<4,>=3.8.1->recommenders) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk<4,>=3.8.1->recommenders) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk<4,>=3.8.1->recommenders) (2025.11.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from notebook<8,>=6.5.5->recommenders) (3.1.6)
Requirement already satisfied: tornado>=6.1 in /usr/local/lib/python3.12/dist-packages (from notebook<8,>=6.5.5->recommenders) (6.5.1)
Requirement already satisfied: argon2-cffi in /usr/local/lib/python3.12/dist-packages (from notebook<8,>=6.5.5->recommenders) (25.1.0)
Requirement already satisfied: traitlets>=4.2.1 in /usr/local/lib/python3.12/dist-packages (from notebook<8,>=6.5.5->recommenders) (5.7.1)
Requirement already satisfied: jupyter-core>=4.6.1 in /usr/local/lib/python3.12/dist-packages (from notebook<8,>=6.5.5->recommenders) (5.9.1)
Requirement already satisfied: jupyter-client<8,>=5.3.4 in /usr/local/lib/python3.12/dist-packages (from notebook<8,>=6.5.5->recommenders) (7.4.9)
Requirement already satisfied: ipython-genutils in /usr/local/lib/python3.12/dist-packages (from notebook<8,>=6.5.5->recommenders) (0.2.0)
Requirement already satisfied: nbformat in /usr/local/lib/python3.12/dist-packages (from notebook<8,>=6.5.5->recommenders) (5.10.4)
Requirement already satisfied: nbconvert>=5 in /usr/local/lib/python3.12/dist-packages (from notebook<8,>=6.5.5->recommenders) (7.17.0)
Requirement already satisfied: nest-asyncio>=1.5 in /usr/local/lib/python3.12/dist-packages (from notebook<8,>=6.5.5->recommenders) (1.6.0)
Requirement already satisfied: ipykernel in /usr/local/lib/python3.12/dist-packages (from notebook<8,>=6.5.5->recommenders) (6.17.1)
Requirement already satisfied: Send2Trash>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from notebook<8,>=6.5.5->recommenders) (2.1.0)
Requirement already satisfied: terminado>=0.8.3 in /usr/local/lib/python3.12/dist-packages (from notebook<8,>=6.5.5->recommenders) (0.18.1)
Requirement already satisfied: prometheus-client in /usr/local/lib/python3.12/dist-packages (from notebook<8,>=6.5.5->recommenders) (0.24.1)
Requirement already satisfied: nbclassic>=0.4.7 in /usr/local/lib/python3.12/dist-packages (from notebook<8,>=6.5.5->recommenders) (1.3.3)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba<1,>=0.57.0->recommenders) (0.43.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0.0,>2.0.0->recommenders) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0.0,>2.0.0->recommenders) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0.0,>2.0.0->recommenders) (2025.3)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from pandera>=0.15.0->pandera[strategies]>=0.15.0; python_version >= "3.9"->recommenders) (26.0)
Requirement already satisfied: pydantic in /usr/local/lib/python3.12/dist-packages (from pandera>=0.15.0->pandera[strategies]>=0.15.0; python_version >= "3.9"->recommenders) (2.12.3)
Requirement already satisfied: typeguard in /usr/local/lib/python3.12/dist-packages (from pandera>=0.15.0->pandera[strategies]>=0.15.0; python_version >= "3.9"->recommenders) (4.5.1)
Requirement already satisfied: typing_extensions in /usr/local/lib/python3.12/dist-packages (from pandera>=0.15.0->pandera[strategies]>=0.15.0; python_version >= "3.9"->recommenders) (4.15.0)
Requirement already satisfied: typing_inspect>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pandera>=0.15.0->pandera[strategies]>=0.15.0; python_version >= "3.9"->recommenders) (0.9.0)
Requirement already satisfied: hypothesis>=6.92.7 in /usr/local/lib/python3.12/dist-packages (from pandera[strategies]>=0.15.0; python_version >= "3.9"->recommenders) (6.151.9)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2,>=1.2.0->recommenders) (3.6.0)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /usr/local/lib/python3.12/dist-packages (from seaborn<1,>=0.13.0->recommenders) (3.10.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers<5,>=4.27.0->recommenders) (3.24.3)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from transformers<5,>=4.27.0->recommenders) (0.36.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers<5,>=4.27.0->recommenders) (6.0.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<5,>=4.27.0->recommenders) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<5,>=4.27.0->recommenders) (0.7.0)
Requirement already satisfied: blinker>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from flask>=2.0.0->locust<3,>=2.12.2->recommenders) (1.9.0)
Requirement already satisfied: itsdangerous>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from flask>=2.0.0->locust<3,>=2.12.2->recommenders) (2.2.0)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from flask>=2.0.0->locust<3,>=2.12.2->recommenders) (3.0.3)
Requirement already satisfied: greenlet>=3.2.2 in /usr/local/lib/python3.12/dist-packages (from gevent!=25.8.1,<26.0.0,>=24.10.1->locust<3,>=2.12.2->recommenders) (3.3.2)
Requirement already satisfied: zope.event in /usr/local/lib/python3.12/dist-packages (from gevent!=25.8.1,<26.0.0,>=24.10.1->locust<3,>=2.12.2->recommenders) (6.1)
Requirement already satisfied: zope.interface in /usr/local/lib/python3.12/dist-packages (from gevent!=25.8.1,<26.0.0,>=24.10.1->locust<3,>=2.12.2->recommenders) (8.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from geventhttpclient>=2.3.1->locust<3,>=2.12.2->recommenders) (2026.2.25)
Requirement already satisfied: brotli in /usr/local/lib/python3.12/dist-packages (from geventhttpclient>=2.3.1->locust<3,>=2.12.2->recommenders) (1.2.0)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.12/dist-packages (from geventhttpclient>=2.3.1->locust<3,>=2.12.2->recommenders) (2.5.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers<5,>=4.27.0->recommenders) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers<5,>=4.27.0->recommenders) (1.3.1)
Requirement already satisfied: sortedcontainers<3.0.0,>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from hypothesis>=6.92.7->pandera[strategies]>=0.15.0; python_version >= "3.9"->recommenders) (2.4.0)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.12/dist-packages (from jupyter-client<8,>=5.3.4->notebook<8,>=6.5.5->recommenders) (0.4)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from jupyter-core>=4.6.1->notebook<8,>=6.5.5->recommenders) (4.9.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn<1,>=0.13.0->recommenders) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn<1,>=0.13.0->recommenders) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn<1,>=0.13.0->recommenders) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn<1,>=0.13.0->recommenders) (1.4.9)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn<1,>=0.13.0->recommenders) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn<1,>=0.13.0->recommenders) (3.3.2)
Requirement already satisfied: notebook-shim>=0.2.3 in /usr/local/lib/python3.12/dist-packages (from nbclassic>=0.4.7->notebook<8,>=6.5.5->recommenders) (0.2.4)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook<8,>=6.5.5->recommenders) (4.13.5)
Requirement already satisfied: bleach!=5.0.0 in /usr/local/lib/python3.12/dist-packages (from bleach[css]!=5.0.0->nbconvert>=5->notebook<8,>=6.5.5->recommenders) (6.3.0)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook<8,>=6.5.5->recommenders) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook<8,>=6.5.5->recommenders) (0.3.0)
Requirement already satisfied: mistune<4,>=2.0.3 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook<8,>=6.5.5->recommenders) (3.2.0)
Requirement already satisfied: nbclient>=0.5.0 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook<8,>=6.5.5->recommenders) (0.10.4)
Requirement already satisfied: pandocfilters>=1.4.1 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook<8,>=6.5.5->recommenders) (1.5.1)
Requirement already satisfied: pygments>=2.4.1 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook<8,>=6.5.5->recommenders) (2.19.2)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.12/dist-packages (from nbformat->notebook<8,>=6.5.5->recommenders) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.12/dist-packages (from nbformat->notebook<8,>=6.5.5->recommenders) (4.26.0)
Requirement already satisfied: iniconfig>=1 in /usr/local/lib/python3.12/dist-packages (from pytest<10,>=8.3.3->locust<3,>=2.12.2->recommenders) (2.3.0)
Requirement already satisfied: pluggy<2,>=1.5 in /usr/local/lib/python3.12/dist-packages (from pytest<10,>=8.3.3->locust<3,>=2.12.2->recommenders) (1.6.0)
Requirement already satisfied: simple-websocket>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from python-engineio>=4.12.2->locust<3,>=2.12.2->recommenders) (1.1.0)
Requirement already satisfied: bidict>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from python-socketio>=5.13.0->python-socketio[client]>=5.13.0->locust<3,>=2.12.2->recommenders) (0.23.1)
Requirement already satisfied: websocket-client>=0.54.0 in /usr/local/lib/python3.12/dist-packages (from python-socketio[client]>=5.13.0->locust<3,>=2.12.2->recommenders) (1.9.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->locust<3,>=2.12.2->recommenders) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->locust<3,>=2.12.2->recommenders) (3.11)
Requirement already satisfied: ptyprocess in /usr/local/lib/python3.12/dist-packages (from terminado>=0.8.3->notebook<8,>=6.5.5->recommenders) (0.7.0)
Requirement already satisfied: mypy-extensions>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from typing_inspect>=0.6.0->pandera>=0.15.0->pandera[strategies]>=0.15.0; python_version >= "3.9"->recommenders) (1.1.0)
Requirement already satisfied: argon2-cffi-bindings in /usr/local/lib/python3.12/dist-packages (from argon2-cffi->notebook<8,>=6.5.5->recommenders) (25.1.0)
Requirement already satisfied: debugpy>=1.0 in /usr/local/lib/python3.12/dist-packages (from ipykernel->notebook<8,>=6.5.5->recommenders) (1.8.15)
Requirement already satisfied: ipython>=7.23.1 in /usr/local/lib/python3.12/dist-packages (from ipykernel->notebook<8,>=6.5.5->recommenders) (7.34.0)
Requirement already satisfied: matplotlib-inline>=0.1 in /usr/local/lib/python3.12/dist-packages (from ipykernel->notebook<8,>=6.5.5->recommenders) (0.2.1)
Requirement already satisfied: mpmath in /usr/local/lib/python3.12/dist-packages (from powerlaw->cornac<3,>=1.15.2->recommenders) (1.3.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic->pandera>=0.15.0->pandera[strategies]>=0.15.0; python_version >= "3.9"->recommenders) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic->pandera>=0.15.0->pandera[strategies]>=0.15.0; python_version >= "3.9"->recommenders) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic->pandera>=0.15.0->pandera[strategies]>=0.15.0; python_version >= "3.9"->recommenders) (0.4.2)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert>=5->notebook<8,>=6.5.5->recommenders) (0.5.1)
Requirement already satisfied: tinycss2<1.5,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from bleach[css]!=5.0.0->nbconvert>=5->notebook<8,>=6.5.5->recommenders) (1.4.0)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel->notebook<8,>=6.5.5->recommenders) (75.2.0)
Requirement already satisfied: jedi>=0.16 in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel->notebook<8,>=6.5.5->recommenders) (0.19.2)
Requirement already satisfied: decorator in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel->notebook<8,>=6.5.5->recommenders) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel->notebook<8,>=6.5.5->recommenders) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel->notebook<8,>=6.5.5->recommenders) (3.0.52)

## 0 Global Settings and Imports

In [1]:
import sys
import os
import recommenders
import pandas as pd
import numpy as np
import tensorflow as tf
tf.get_logger().setLevel('ERROR') # only show error messages

from recommenders.utils.timer import Timer
from recommenders.models.deeprec.models.graphrec.lightgcn import LightGCN
from recommenders.models.deeprec.DataModel.ImplicitCF import ImplicitCF
from recommenders.datasets import movielens
from recommenders.datasets.python_splitters import python_stratified_split
from recommenders.evaluation.python_evaluation import map, ndcg_at_k, precision_at_k, recall_at_k
from recommenders.utils.constants import SEED as DEFAULT_SEED
from recommenders.models.deeprec.deeprec_utils import prepare_hparams
from recommenders.utils.notebook_utils import store_metadata

print(f"System version: {sys.version}")
print(f"Pandas version: {pd.__version__}")
print(f"Tensorflow version: {tf.__version__}")

System version: 3.12.12 (main, Oct 10 2025, 08:52:57) [GCC 11.4.0]
Pandas version: 2.2.2
Tensorflow version: 2.19.0

/usr/local/lib/python3.12/dist-packages/pandera/_pandas_deprecated.py:157: FutureWarning: Importing pandas-specific classes and functions from the
top-level pandera module will be **removed in a future version of pandera**.
If you're using pandera to validate pandas objects, we highly recommend updating
your import:

```
# old import
import pandera as pa

# new import
import pandera.pandas as pa
```

If you're using pandera to validate objects from other compatible libraries
like pyspark or polars, see the supported libraries section of the documentation
for more information on how to import pandera:

https://pandera.readthedocs.io/en/stable/supported_libraries.html

To disable this warning, set the environment variable:

```
export DISABLE_PANDERA_IMPORT_WARNING=True
```

  warnings.warn(_future_warning, FutureWarning)

In [2]:
# top k items to recommend
TOP_K = 10

# Select MovieLens data size: 100k, 1m, 10m, or 20m
MOVIELENS_DATA_SIZE = '100k'

# Model parameters
EPOCHS = 50
BATCH_SIZE = 1024

SEED = DEFAULT_SEED  # Set None for non-deterministic results

# Download the lightgcn.yaml file from GitHub
!wget -q -O /content/lightgcn.yaml https://raw.githubusercontent.com/microsoft/recommenders/main/recommenders/models/deeprec/config/lightgcn.yaml

yaml_file = "/content/lightgcn.yaml"
user_file = "../../tests/resources/deeprec/lightgcn/user_embeddings.csv"
item_file = "../../tests/resources/deeprec/lightgcn/item_embeddings.csv"

## 1 LightGCN model

LightGCN is a simplified version of Neural Graph Collaborative Filtering (NGCF) [4], which adapts GCNs in recommendation systems.

### 1.1 Graph Networks in Recommendation Systems

GCN are networks that can learn patterns in graph data. They can be applied in many fields, but they are particularly well suited for Recommendation Systems, because of their ability to encode relationships.

In traditional models like matrix factorization [5], user and items are represented as embeddings. And the interaction, which is the signal that encodes the behavior, is not part of the embeddings, but it is represented in the loss function, typically as a dot product.

Despite their effectiveness, some authors [1,4] argue that these methods are not sufficient to yield satisfactory embeddings for collaborative filtering. The key reason is that the embedding function lacks an explicit encoding of the crucial collaborative signal, which is latent in user-item interactions to reveal the behavioral similarity between users (or items).

**GCNs can be used to encode the interaction signal in the embeddings**. Interacted items can be seen as user´s features, because they provide direct evidence on a user’s preference. Similarly, the users that consume an item can be treated as the item’s features and used to measure the collaborative similarity of two items. A natural way to incorporate the interaction signal in the embedding is by exploiting the high-order connectivity from user-item interactions.

In the figure below, the user-item interaction is shown (to the left) as well as the concept of higher-order connectivity (to the right).

<img src="https://raw.githubusercontent.com/recommenders-team/resources/main/images/High_order_connectivity.png" width=500 style="display:block; margin-left:auto; margin-right:auto;">

The high-order connectivity shows the collaborative signal in a graph form. For example, the path $u_1 ← i_2 ← u2$ indicates the behavior
similarity between $u_1$ and $u_2$, as both users have interacted with $i_2$; the longer path $u_1 ← i_2 ← u_2 ← i_4$ suggests that $u_1$ is likely to adopt $i_4$, since her similar user $u_2$ has consumed $i_4$ before. Moreover, from the holistic view of $l = 3$, item $i_4$ is more likely to be of interest to $u_1$ than item $i_5$, since there are two paths connecting $(i_4,u_1)$, while only one path connects $(i_5,u_1)$.

Based on this high-order connectivity, NGCF [4] defines an embedding propagation layer, which refines a user’s (or an item’s) embedding by aggregating the embeddings of the interacted items (or users). By stacking multiple embedding propagation layers, we can enforce the embeddings
to capture the collaborative signal in high-order connectivities.

More formally, let $\mathbf{e}_{u}^{0}$ denote the original embedding of user $u$ and $\mathbf{e}_{i}^{0}$ denote the original embedding of item $i$. The embedding propagation can be computed recursively as:

$$
\begin{array}{l}
\mathbf{e}_{u}^{(k+1)}=\sigma\bigl( \mathbf{W}_{1}\mathbf{e}_{u}^{(k)} + \sum_{i \in \mathcal{N}_{u}} \frac{1}{\sqrt{\left|\mathcal{N}_{u}\right|} \sqrt{\left|\mathcal{N}_{i}\right|}} (\mathbf{W}_{1}\mathbf{e}_{i}^{(k)} + \mathbf{W}_{2}(\mathbf{e}_{i}^{(k)}\cdot\mathbf{e}_{u}^{(k)}) ) \bigr)
\\
\mathbf{e}_{i}^{(k+1)}=\sigma\bigl( \mathbf{W}_{1}\mathbf{e}_{i}^{(k)} +\sum_{u \in \mathcal{N}_{i}} \frac{1}{\sqrt{\left|\mathcal{N}_{i}\right|} \sqrt{\left|\mathcal{N}_{u}\right|}} (\mathbf{W}_{1}\mathbf{e}_{u}^{(k)} + \mathbf{W}_{2}(\mathbf{e}_{u}^{(k)}\cdot\mathbf{e}_{i}^{(k)}) ) \bigr)
\end{array}
$$

where $\mathbf{W}_{1}$ and $\mathbf{W}_{2}$ are trainable weight matrices, $\frac{1}{\sqrt{\left|\mathcal{N}_{i}\right|} \sqrt{\left|\mathcal{N}_{u}\right|}}$ is a discount factor expressed as the graph Laplacian norm, $\mathcal{N}_{u}$ and $\mathcal{N}_{i}$ denote the first-hop neighbors of user $u$ and item $i$, and $\sigma$ is a non-linearity that in the paper is set as a LeakyReLU.

To obtain the final representation, each propagated embedding is concatenated (i.e., $\mathbf{e}_{u}^{(*)}=\mathbf{e}_{u}^{(0)}||...||\mathbf{e}_{u}^{(l)}$), and then the final user's preference over an item is computed as a dot product: $\hat y_{u i} = \mathbf{e}_{u}^{(*)T}\mathbf{e}_{i}^{(*)}$.

### 1.2 LightGCN architecture

LightGCN is a simplified version of NGCF [4] to make it more concise and appropriate for recommendations. The model architecture is illustrated below.

<img src="https://raw.githubusercontent.com/recommenders-team/resources/main/images/lightGCN-model.jpg" width=600 style="display:block; margin-left:auto; margin-right:auto;">

In Light Graph Convolution, only the normalized sum of neighbor embeddings is performed towards next layer; other operations like self-connection, feature transformation via weight matrices, and nonlinear activation are all removed, which largely simplifies NGCF. In the layer combination step, instead of concatenating the embeddings, we sum over the embeddings at each layer to obtain the final representations.

### 1.3 Light Graph Convolution (LGC)

In LightGCN, we adopt the simple weighted sum aggregator and abandon the use of feature transformation and nonlinear activation. The graph convolution operation in LightGCN is defined as:

$$
\begin{array}{l}
\mathbf{e}_{u}^{(k+1)}=\sum_{i \in \mathcal{N}_{u}} \frac{1}{\sqrt{\left|\mathcal{N}_{u}\right|} \sqrt{\left|\mathcal{N}_{i}\right|}} \mathbf{e}_{i}^{(k)} \\
\mathbf{e}_{i}^{(k+1)}=\sum_{u \in \mathcal{N}_{i}} \frac{1}{\sqrt{\left|\mathcal{N}_{i}\right|} \sqrt{\left|\mathcal{N}_{u}\right|}} \mathbf{e}_{u}^{(k)}
\end{array}
$$

The symmetric normalization term $\frac{1}{\sqrt{\left|\mathcal{N}_{u}\right|} \sqrt{\left|\mathcal{N}_{i}\right|}}$ follows the design of standard GCN, which can avoid the scale of embeddings increasing with graph convolution operations.


### 1.4 Layer Combination and Model Prediction

In LightGCN, the only trainable model parameters are the embeddings at the 0-th layer, i.e., $\mathbf{e}_{u}^{(0)}$ for all users and $\mathbf{e}_{i}^{(0)}$ for all items. When they are given, the embeddings at higher layers can be computed via LGC. After $K$ layers LGC, we further combine the embeddings obtained at each layer to form the final representation of a user (an item):

$$
\mathbf{e}_{u}=\sum_{k=0}^{K} \alpha_{k} \mathbf{e}_{u}^{(k)} ; \quad \mathbf{e}_{i}=\sum_{k=0}^{K} \alpha_{k} \mathbf{e}_{i}^{(k)}
$$

where $\alpha_{k} \geq 0$ denotes the importance of the $k$-th layer embedding in constituting the final embedding. In our experiments, we set $\alpha_{k}$ uniformly as $1 / (K+1)$.

The model prediction is defined as the inner product of user and item final representations:

$$
\hat{y}_{u i}=\mathbf{e}_{u}^{T} \mathbf{e}_{i}
$$

which is used as the ranking score for recommendation generation.


### 1.5 Matrix Form

Let the user-item interaction matrix be $\mathbf{R} \in \mathbb{R}^{M \times N}$ where $M$ and $N$ denote the number of users and items, respectively, and each entry $R_{ui}$ is 1 if $u$ has interacted with item $i$ otherwise 0. We then obtain the adjacency matrix of the user-item graph as

$$
\mathbf{A}=\left(\begin{array}{cc}
\mathbf{0} & \mathbf{R} \\
\mathbf{R}^{T} & \mathbf{0}
\end{array}\right)
$$

Let the 0-th layer embedding matrix be $\mathbf{E}^{(0)} \in \mathbb{R}^{(M+N) \times T}$, where $T$ is the embedding size. Then we can obtain the matrix equivalent form of LGC as:

$$
\mathbf{E}^{(k+1)}=\left(\mathbf{D}^{-\frac{1}{2}} \mathbf{A} \mathbf{D}^{-\frac{1}{2}}\right) \mathbf{E}^{(k)}
$$

where $\mathbf{D}$ is a $(M+N) \times(M+N)$ diagonal matrix, in which each entry $D_{ii}$ denotes the number of nonzero entries in the $i$-th row vector of the adjacency matrix $\mathbf{A}$ (also named as degree matrix). Lastly, we get the final embedding matrix used for model prediction as:

$$
\begin{aligned}
\mathbf{E} &=\alpha_{0} \mathbf{E}^{(0)}+\alpha_{1} \mathbf{E}^{(1)}+\alpha_{2} \mathbf{E}^{(2)}+\ldots+\alpha_{K} \mathbf{E}^{(K)} \\
&=\alpha_{0} \mathbf{E}^{(0)}+\alpha_{1} \tilde{\mathbf{A}} \mathbf{E}^{(0)}+\alpha_{2} \tilde{\mathbf{A}}^{2} \mathbf{E}^{(0)}+\ldots+\alpha_{K} \tilde{\mathbf{A}}^{K} \mathbf{E}^{(0)}
\end{aligned}
$$

where $\tilde{\mathbf{A}}=\mathbf{D}^{-\frac{1}{2}} \mathbf{A} \mathbf{D}^{-\frac{1}{2}}$ is the symmetrically normalized matrix.

### 1.6 Model Training

We employ the Bayesian Personalized Ranking (BPR) loss which is a pairwise loss that encourages the prediction of an observed entry to be higher than its unobserved counterparts:

$$
L_{B P R}=-\sum_{u=1}^{M} \sum_{i \in \mathcal{N}_{u}} \sum_{j \notin \mathcal{N}_{u}} \ln \sigma\left(\hat{y}_{u i}-\hat{y}_{u j}\right)+\lambda\left\|\mathbf{E}^{(0)}\right\|^{2}
$$

Where $\lambda$ controls the $L_2$ regularization strength. We employ the Adam optimizer and use it in a mini-batch manner.

## 2 TensorFlow implementation of LightGCN with MovieLens dataset

We will use the MovieLens dataset, which is composed of integer ratings from 1 to 5.

We convert MovieLens into implicit feedback for model training and evaluation.

### 2.1 Load and split data

We split the full dataset into a `train` and `test` dataset to evaluate performance of the algorithm against a held-out set not seen during training. Because SAR generates recommendations based on user preferences, all users that are in the test set must also exist in the training set. For this case, we can use the provided `python_stratified_split` function which holds out a percentage (in this case 25%) of items from each user, but ensures all users are in both `train` and `test` datasets. Other options are available in the `dataset.python_splitters` module which provide more control over how the split occurs.

In [3]:
df = movielens.load_pandas_df(size=MOVIELENS_DATA_SIZE)

df.head()

100%|██████████| 4.81k/4.81k [00:01<00:00, 3.60kKB/s]

   userID  itemID  rating  timestamp
0     196     242     3.0  881250949
1     186     302     3.0  891717742
2      22     377     1.0  878887116
3     244      51     2.0  880606923
4     166     346     1.0  886397596

In [4]:
train, test = python_stratified_split(df, ratio=0.75)

### 2.2 Process data

`ImplicitCF` is a class that intializes and loads data for the training process. During the initialization of this class, user IDs and item IDs are reindexed, ratings greater than zero are converted into implicit positive interaction, and adjacency matrix $R$ of user-item graph is created. Some important methods of `ImplicitCF` are:

`get_norm_adj_mat`, load normalized adjacency matrix of user-item graph if it already exists in `adj_dir`, otherwise call `create_norm_adj_mat` to create the matrix and save the matrix if `adj_dir` is not `None`. This method will be called during the initialization process of LightGCN model.

`create_norm_adj_mat`, create normalized adjacency matrix of user-item graph by calculating $D^{-\frac{1}{2}} A D^{-\frac{1}{2}}$, where $\mathbf{A}=\left(\begin{array}{cc}\mathbf{0} & \mathbf{R} \\ \mathbf{R}^{T} & \mathbf{0}\end{array}\right)$.

`train_loader`, generate a batch of training data — sample a batch of users and then sample one positive item and one negative item for each user. This method will be called before each epoch of the training process.

In [5]:
data = ImplicitCF(train=train, test=test, seed=SEED)

### 2.3 Prepare hyper-parameters

Important parameters of `LightGCN` model are:

`data`, initialized LightGCNDataset object.

`epochs`, number of epochs for training.

`n_layers`, number of layers of the model.

`eval_epoch`, if it is not None, evaluation metrics will be calculated on test set every "eval_epoch" epochs. In this way, we can observe the effect of the model during the training process.

`top_k`, the number of items to be recommended for each user when calculating ranking metrics.

A complete list of parameters can be found in `yaml_file`. We use `prepare_hparams` to read the yaml file and prepare a full set of parameters for the model. Parameters passed as the function's parameters will overwrite yaml settings.

In [6]:
import os
import recommenders

hparams = prepare_hparams(yaml_file,
                          n_layers=3,
                          batch_size=BATCH_SIZE,
                          epochs=EPOCHS,
                          learning_rate=0.005,
                          eval_epoch=5,
                          top_k=TOP_K
                         )

### 2.4 Create and train model

With data and parameters prepared, we can create the LightGCN model.

To train the model, we simply need to call the `fit()` method.

In [7]:
model = LightGCN(hparams, data, seed=SEED)

Already create adjacency matrix.
Already normalize adjacency matrix.
Using xavier initialization.

In [8]:
with Timer() as train_time:
    model.fit()

print("Took {} seconds for training.".format(train_time.interval))

Epoch 1 (train)1.4s: train loss = 0.47168 = (mf)0.47143 + (embed)0.00024
Epoch 2 (train)1.2s: train loss = 0.29010 = (mf)0.28947 + (embed)0.00063
Epoch 3 (train)1.2s: train loss = 0.25365 = (mf)0.25286 + (embed)0.00079
Epoch 4 (train)1.7s: train loss = 0.23849 = (mf)0.23752 + (embed)0.00097
Epoch 5 (train)1.2s + (eval)0.3s: train loss = 0.22635 = (mf)0.22525 + (embed)0.00111, recall = 0.15604, ndcg = 0.34528, precision = 0.29873, map = 0.21589
Epoch 6 (train)1.2s: train loss = 0.21993 = (mf)0.21872 + (embed)0.00122
Epoch 7 (train)1.2s: train loss = 0.21247 = (mf)0.21115 + (embed)0.00133
Epoch 8 (train)1.2s: train loss = 0.20166 = (mf)0.20020 + (embed)0.00146
Epoch 9 (train)1.2s: train loss = 0.18961 = (mf)0.18799 + (embed)0.00162
Epoch 10 (train)1.2s + (eval)0.2s: train loss = 0.18167 = (mf)0.17989 + (embed)0.00179, recall = 0.17587, ndcg = 0.38822, precision = 0.33934, map = 0.25166
Epoch 11 (train)1.2s: train loss = 0.17129 = (mf)0.16935 + (embed)0.00194
Epoch 12 (train)1.5s: train loss = 0.16968 = (mf)0.16759 + (embed)0.00209
Epoch 13 (train)1.4s: train loss = 0.16617 = (mf)0.16396 + (embed)0.00221
Epoch 14 (train)1.2s: train loss = 0.16545 = (mf)0.16313 + (embed)0.00232
Epoch 15 (train)1.3s + (eval)0.2s: train loss = 0.16116 = (mf)0.15875 + (embed)0.00241, recall = 0.18458, ndcg = 0.40379, precision = 0.35090, map = 0.26510
Epoch 16 (train)1.2s: train loss = 0.16134 = (mf)0.15882 + (embed)0.00251
Epoch 17 (train)1.2s: train loss = 0.15985 = (mf)0.15725 + (embed)0.00260
Epoch 18 (train)1.2s: train loss = 0.15368 = (mf)0.15099 + (embed)0.00269
Epoch 19 (train)1.2s: train loss = 0.15133 = (mf)0.14853 + (embed)0.00280
Epoch 20 (train)1.3s + (eval)0.2s: train loss = 0.15087 = (mf)0.14798 + (embed)0.00288, recall = 0.18917, ndcg = 0.41081, precision = 0.35737, map = 0.27083
Epoch 21 (train)1.8s: train loss = 0.14900 = (mf)0.14603 + (embed)0.00298
Epoch 22 (train)1.2s: train loss = 0.14541 = (mf)0.14232 + (embed)0.00309
Epoch 23 (train)1.2s: train loss = 0.14408 = (mf)0.14089 + (embed)0.00320
Epoch 24 (train)1.3s: train loss = 0.13858 = (mf)0.13528 + (embed)0.00330
Epoch 25 (train)1.2s + (eval)0.5s: train loss = 0.13870 = (mf)0.13528 + (embed)0.00342, recall = 0.19689, ndcg = 0.42342, precision = 0.36978, map = 0.28242
Epoch 26 (train)1.2s: train loss = 0.13670 = (mf)0.13317 + (embed)0.00354
Epoch 27 (train)1.3s: train loss = 0.13430 = (mf)0.13065 + (embed)0.00365
Epoch 28 (train)1.2s: train loss = 0.13218 = (mf)0.12842 + (embed)0.00376
Epoch 29 (train)1.6s: train loss = 0.13249 = (mf)0.12863 + (embed)0.00386
Epoch 30 (train)1.4s + (eval)0.2s: train loss = 0.12881 = (mf)0.12482 + (embed)0.00399, recall = 0.20238, ndcg = 0.43656, precision = 0.37985, map = 0.29477
Epoch 31 (train)1.3s: train loss = 0.12755 = (mf)0.12346 + (embed)0.00409
Epoch 32 (train)1.2s: train loss = 0.12605 = (mf)0.12183 + (embed)0.00422
Epoch 33 (train)1.2s: train loss = 0.12559 = (mf)0.12126 + (embed)0.00433
Epoch 34 (train)1.2s: train loss = 0.12141 = (mf)0.11696 + (embed)0.00445
Epoch 35 (train)1.2s + (eval)0.2s: train loss = 0.12109 = (mf)0.11653 + (embed)0.00457, recall = 0.20451, ndcg = 0.43974, precision = 0.38420, map = 0.29790
Epoch 36 (train)1.2s: train loss = 0.11732 = (mf)0.11263 + (embed)0.00469
Epoch 37 (train)1.2s: train loss = 0.11915 = (mf)0.11435 + (embed)0.00480
Epoch 38 (train)1.7s: train loss = 0.11773 = (mf)0.11282 + (embed)0.00492
Epoch 39 (train)1.2s: train loss = 0.11122 = (mf)0.10616 + (embed)0.00506
Epoch 40 (train)1.2s + (eval)0.2s: train loss = 0.11425 = (mf)0.10907 + (embed)0.00518, recall = 0.20962, ndcg = 0.44706, precision = 0.38929, map = 0.30428
Epoch 41 (train)1.3s: train loss = 0.11097 = (mf)0.10567 + (embed)0.00530
Epoch 42 (train)1.2s: train loss = 0.10831 = (mf)0.10287 + (embed)0.00544
Epoch 43 (train)1.2s: train loss = 0.10932 = (mf)0.10376 + (embed)0.00555
Epoch 44 (train)1.2s: train loss = 0.10470 = (mf)0.09902 + (embed)0.00568
Epoch 45 (train)1.2s + (eval)0.2s: train loss = 0.10536 = (mf)0.09955 + (embed)0.00581, recall = 0.21075, ndcg = 0.45333, precision = 0.39406, map = 0.30951
Epoch 46 (train)1.4s: train loss = 0.10619 = (mf)0.10026 + (embed)0.00593
Epoch 47 (train)1.5s: train loss = 0.10427 = (mf)0.09821 + (embed)0.00605
Epoch 48 (train)1.3s: train loss = 0.10272 = (mf)0.09654 + (embed)0.00618
Epoch 49 (train)1.2s: train loss = 0.09851 = (mf)0.09219 + (embed)0.00632
Epoch 50 (train)1.2s + (eval)0.2s: train loss = 0.09715 = (mf)0.09070 + (embed)0.00645, recall = 0.21631, ndcg = 0.45835, precision = 0.39958, map = 0.31335
Took 66.72511228199983 seconds for training.

### 2.5 Recommendation and Evaluation

Recommendation and evaluation have been performed on the specified test set during training. After training, we can also use the model to perform recommendation and evalution on other data. Here we still use `test` as test data, but `test` can be replaced by other data with similar data structure.

#### 2.5.1 Recommendation

We can call `recommend_k_items` to recommend k items for each user passed in this function. We set `remove_seen=True` to remove the items already seen by the user. The function returns a dataframe, containing each user and top k items recommended to them and the corresponding ranking scores.

In [9]:
topk_scores = model.recommend_k_items(test, top_k=TOP_K, remove_seen=True)

topk_scores.head()

   userID  itemID  prediction
0       1     174    5.740654
1       1     181    5.675140
2       1      98    5.395623
3       1     204    5.270529
4       1     475    5.208995

#### 2.5.2 Evaluation

With `topk_scores` predicted by the model, we can evaluate how LightGCN performs on this test set.

In [11]:
eval_map = map(test, topk_scores, k=TOP_K)
eval_ndcg = ndcg_at_k(test, topk_scores, k=TOP_K)
eval_precision = precision_at_k(test, topk_scores, k=TOP_K)
eval_recall = recall_at_k(test, topk_scores, k=TOP_K)

print("MAP:\t%f" % eval_map,
      "NDCG:\t%f" % eval_ndcg,
      "Precision@K:\t%f" % eval_precision,
      "Recall@K:\t%f" % eval_recall, sep='\n')

MAP:	0.139610
NDCG:	0.458353
Precision@K:	0.399576
Recall@K:	0.216312

In [12]:
# Record results for tests - ignore this cell
store_metadata("map", eval_map)
store_metadata("ndcg", eval_ndcg)
store_metadata("precision", eval_precision)
store_metadata("recall", eval_recall)

### 2.6 Infer embeddings

With `infer_embedding` method of LightGCN model, we can export the embeddings of users and items in the training set to CSV files for future use.

In [ ]:
model.infer_embedding(user_file, item_file)

## 3. Compare LightGCN with SAR and NCF

Here there are the performances of LightGCN compared to [SAR](../00_quick_start/sar_movielens.ipynb) and [NCF](../00_quick_start/ncf_movielens.ipynb) on MovieLens dataset of 100k and 1m. The method of data loading and splitting is the same as that described above and the GPU used was a GeForce GTX 1080Ti.

Settings common to the three models: `epochs=15, seed=42`.

Settings for LightGCN: `embed_size=64, n_layers=3, batch_size=1024, decay=0.0001, learning_rate=0.015 `.

Settings for SAR: `similarity_type="jaccard", time_decay_coefficient=30, time_now=None, timedecay_formula=True`.

Settings for NCF: `n_factors=4, layer_sizes=[16, 8, 4], batch_size=1024, learning_rate=0.001`.

| Data Size | Model    | Training time | Recommending time | MAP@10   | nDCG@10  | Precision@10 | Recall@10 |
| --------- | -------- | ------------- | ----------------- | -------- | -------- | ------------ | --------- |
| 100k      | LightGCN | 27.8865       | 0.6445            | 0.129236 | 0.436297 | 0.381866     | 0.205816  |
| 100k      | SAR      | 0.4895        | 0.1144            | 0.110591 | 0.382461 | 0.330753     | 0.176385  |
| 100k      | NCF      | 116.3174      | 7.7660            | 0.105725 | 0.387603 | 0.342100     | 0.174580  |
| 1m        | LightGCN | 396.7298      | 1.4343            | 0.075012 | 0.377501 | 0.345679     | 0.128096  |
| 1m        | SAR      | 4.5593        | 2.8357            | 0.060579 | 0.299245 | 0.270116     | 0.104350  |
| 1m        | NCF      | 1601.5846     | 85.4567           | 0.062821 | 0.348770 | 0.320613     | 0.108121  |

From the above results, we can see that LightGCN performs better than the other two models.

### References:
1. Xiangnan He, Kuan Deng, Xiang Wang, Yan Li, Yongdong Zhang & Meng Wang, LightGCN: Simplifying and Powering Graph Convolution Network for Recommendation, 2020, https://arxiv.org/abs/2002.02126
2. LightGCN implementation [TensorFlow]: https://github.com/kuandeng/lightgcn
3. Thomas N. Kipf and Max Welling, Semi-Supervised Classification with Graph Convolutional Networks, ICLR, 2017, https://arxiv.org/abs/1609.02907
4. Xiang Wang, Xiangnan He, Meng Wang, Fuli Feng, and Tat-Seng Chua, Neural Graph Collaborative Filtering, SIGIR, 2019, https://arxiv.org/abs/1905.08108
5. Y. Koren, R. Bell and C. Volinsky, "Matrix Factorization Techniques for Recommender Systems", in Computer, vol. 42, no. 8, pp. 30-37, Aug. 2009, doi: 10.1109/MC.2009.263.  url: https://datajobs.com/data-science-repo/Recommender-Systems-%5BNetflix%5D.pdf

In [15]:
# Trying to back up everything on local drive
!pip freeze > requirements.txt
from google.colab import files
files.download("requirements.txt")

In [16]:
# Save in google drive
from google.colab import drive
drive.mount('/content/drive')
#save files
!cp -r /content/lightgcn.yaml /content/drive/MyDrive

Mounted at /content/drive